/* tslint:disable */
/* eslint-disable */
/*
API Settings

At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.

BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.

And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.

With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners. 

Learn more at BlueSnap.com

The version of the OpenAPI document: 8976-Tools


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { ReversalAuthTransactionRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * ReversalApi - axios parameter creator
 * @export
 */
export const ReversalApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Auth Reversal
         * @param {ReversalAuthTransactionRequest} [reversalAuthTransactionRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTransaction: async (reversalAuthTransactionRequest?: ReversalAuthTransactionRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/transactions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication sec0 required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)
            // authentication sec1 required
            await setApiKeyToObject({ object: localVarHeaderParameter, key: "Authorization", keyParamName: "sec1", configuration })

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: reversalAuthTransactionRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration,
                pathTemplate: '/transactions',
                httpMethod: 'PUT'
            });
            localVarRequestOptions.data = serializeDataIfNeeded(reversalAuthTransactionRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReversalApi - functional programming interface
 * @export
 */
export const ReversalApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReversalApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Auth Reversal
         * @param {ReversalApiAuthTransactionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authTransaction(requestParameters: ReversalApiAuthTransactionRequest = {}, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const reversalAuthTransactionRequest: ReversalAuthTransactionRequest = {
                cardTransactionType: requestParameters.cardTransactionType,
                transactionId: requestParameters.transactionId
            };
            const localVarAxiosArgs = await localVarAxiosParamCreator.authTransaction(reversalAuthTransactionRequest, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * ReversalApi - factory interface
 * @export
 */
export const ReversalApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReversalApiFp(configuration)
    return {
        /**
         * 
         * @summary Auth Reversal
         * @param {ReversalApiAuthTransactionRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authTransaction(requestParameters: ReversalApiAuthTransactionRequest = {}, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.authTransaction(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for authTransaction operation in ReversalApi.
 * @export
 * @interface ReversalApiAuthTransactionRequest
 */
export type ReversalApiAuthTransactionRequest = {
    
} & ReversalAuthTransactionRequest

/**
 * ReversalApiGenerated - object-oriented interface
 * @export
 * @class ReversalApiGenerated
 * @extends {BaseAPI}
 */
export class ReversalApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Auth Reversal
     * @param {ReversalApiAuthTransactionRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReversalApiGenerated
     */
    public authTransaction(requestParameters: ReversalApiAuthTransactionRequest = {}, options?: AxiosRequestConfig) {
        return ReversalApiFp(this.configuration).authTransaction(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
