/*
API Settings

At BlueSnap, we look at payments a little differently. Our Payment Orchestration Platform helps businesses accept payments globally and is designed to increase revenue and reduces costs. We provide a comprehensive back-end solutions that simplifies the complexity of payments, managing the full process from start to finish.

BlueSnap supports payments through multiple sales channels such as online and mobile sales, marketplaces, subscriptions, invoice payments and manual orders through a virtual terminal. And for businesses looking for embedded payments, we offer white-labeled payments for platforms with automated underwriting and onboarding that supports marketplaces and split payments.

And with one integration and contract, businesses can sell in over 200 geographies with access to local acquiring in 47 countries, 110+ currencies and 100+ global payment types, including popular eWallets, automated accounts receivable, world-class fraud protection and chargeback management, built-in solutions for regulation and tax compliance, and unified global reporting to help businesses grow.

With a US headquarters in Waltham, MA, and EU headquarters in Dublin, Ireland, BlueSnap is backed by world-class private equity investors including Great Hill Partners and Parthenon Capital Partners. 

Learn more at BlueSnap.com

The version of the OpenAPI document: 8976-Tools


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction } from './transaction-create-sofort-transaction-request-acss-direct-debit-transaction';
import { TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction } from './transaction-create-sofort-transaction-request-becs-direct-debit-transaction';
import { TransactionCreateSofortTransactionRequestEcpTransaction } from './transaction-create-sofort-transaction-request-ecp-transaction';
import { TransactionCreateSofortTransactionRequestIdealTransaction } from './transaction-create-sofort-transaction-request-ideal-transaction';
import { TransactionCreateSofortTransactionRequestLocalBankTransferTransaction } from './transaction-create-sofort-transaction-request-local-bank-transfer-transaction';
import { TransactionCreateSofortTransactionRequestPayerInfo } from './transaction-create-sofort-transaction-request-payer-info';
import { TransactionCreateSofortTransactionRequestPaypalTransaction } from './transaction-create-sofort-transaction-request-paypal-transaction';
import { TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction } from './transaction-create-sofort-transaction-request-sepa-direct-debit-transaction';
import { TransactionCreateSofortTransactionRequestSofortTransaction } from './transaction-create-sofort-transaction-request-sofort-transaction';

/**
 * 
 * @export
 * @interface TransactionCreateSofortTransactionRequest
 */
export interface TransactionCreateSofortTransactionRequest {
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestEcpTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'ecpTransaction'?: TransactionCreateSofortTransactionRequestEcpTransaction;
    /**
     * 
     * @type {number}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'amount'?: number;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestPayerInfo}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'payerInfo'?: TransactionCreateSofortTransactionRequestPayerInfo;
    /**
     * 
     * @type {string}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'softDescriptor'?: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'currency'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'authorizedByShopper'?: boolean;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'becsDirectDebitTransaction'?: TransactionCreateSofortTransactionRequestBecsDirectDebitTransaction;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestIdealTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'idealTransaction'?: TransactionCreateSofortTransactionRequestIdealTransaction;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestLocalBankTransferTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'localBankTransferTransaction'?: TransactionCreateSofortTransactionRequestLocalBankTransferTransaction;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestPaypalTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'paypalTransaction'?: TransactionCreateSofortTransactionRequestPaypalTransaction;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'acssDirectDebitTransaction'?: TransactionCreateSofortTransactionRequestAcssDirectDebitTransaction;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'sepaDirectDebitTransaction'?: TransactionCreateSofortTransactionRequestSepaDirectDebitTransaction;
    /**
     * 
     * @type {TransactionCreateSofortTransactionRequestSofortTransaction}
     * @memberof TransactionCreateSofortTransactionRequest
     */
    'sofortTransaction'?: TransactionCreateSofortTransactionRequestSofortTransaction;
}

